name: Copy Repository to Hosted Runner

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  copy-repo:
    runs-on: self-hosted # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy repository to runner
      run: |
        # Create a directory to copy the repository to
        ls
        pwd
        npm install
    - name: Check if Node.js app is running
      run: |
          pm2 list > pm2_list.txt
          if grep -q "server" pm2_list.txt; then
            echo "Your Node.js app is running. Stopping it..."
            pm2 stop server
            pm2 delete server
            echo "Your Node.js app has been stopped."
          else
            echo "Your Node.js app is not running."
          fi
    - name: =Node.js app is Starting
      run: |
        pm2 start server.js
