name: Deloy Node Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\[(BUGFIX|DOCS|FEATURE|TASK)\] .+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "[(BUGFIX|DOCS|FEATURE|TASK)]".'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.TOKEN }}
  # copy-repo:
  #   runs-on: self-hosted # You can choose a different runner if needed
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
      
  #   - name: Install Dependancy
  #     run: |
  #       npm install

  #   - name: Check if Node.js app is running
  #     run: |
  #         pm2 list > pm2_list.txt
  #         if grep -wq "index" pm2_list.txt; then
  #           echo "Your Node.js app is running. Stopping it..."
  #           pm2 stop index
  #           pm2 delete index
  #           echo "Your Node.js app has been stopped."
  #         else
  #           echo "Your Node.js app is not running."
  #         fi

  #   - name: Node.js app is Starting
  #     run: |
  #       pm2 start index.js

    # - name: Save PM2 process list
    #   run: pm2 list
